### ISSUE TITLE
Cannot find module 'node_modules/inline-chunk-html-plugin/lib/index.js'.

### ISSUE THREAD

**Issue by weilinzung** [pikadun/InlineChunkHtmlPlugin#1]
Cannot find module 'node_modules/inline-chunk-html-plugin/lib/index.js'.
Please verify that the package.json has a valid "main" entry

"inline-chunk-html-plugin": "^1.0.4",

**Comment by pikadun** [comment]
The file `lib/index.js` is missing, I released a new version to solve this problem.
